### ISSUE TITLE
NameError: name 'long' is not defined

### ISSUE THREAD

**Issue by danbst** [SirAnthony/slpp#26]
Tests fail in python 3.7:
```
======================================================================                         
ERROR: test_unicode (tests.TestSLPP)
----------------------------------------------------------------------                    
Traceback (most recent call last):                                                             
  File "/build/source/tests.py", line 147, in test_unicode
    self.assertEqual(slpp.encode({'s': u'Привет'}), '{\n\ts = "Привет"\n}')                    
  File "/build/source/slpp.py", line 58, in encode  
    return self.__encode(obj)                                                                  
  File "/build/source/slpp.py", line 87, in __encode                       
    key = '[%s]' if all(isinstance(k, (int, long)) for k in obj.keys()) else '%s'              
  File "/build/source/slpp.py", line 87, in <genexpr>
    key = '[%s]' if all(isinstance(k, (int, long)) for k in obj.keys()) else '%s'
NameError: name 'long' is not defined                                                          
```
I guess this is because python3 no longer has long type (https://www.python.org/dev/peps/pep-0237/)

**Comment by SirAnthony** [comment]
Should be fixed
