### ISSUE TITLE
Installing from sdist is broken

### ISSUE THREAD

**Issue by layday** [SirAnthony/slpp#27]
`README.markdown` is not included in the source distribution tarball which `setuptools` attempts to read; this is when invoking `python -m pip install --no-binary :all: slpp==1.2`:

```
...
    ERROR: Command errored out with exit status 1:
     command: /nix/store/jwabyfhz3h2864i4mns3l64a71nc7rwl-python3-3.7.7-env/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/tmpwfrovct9/pip-download-4i8hnkw9/slpp/setup.py'"'"'; __file__='"'"'/tmp/tmpwfrovct9/pip-download-4i8hnkw9/slpp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/tmpwfrovct9/pip-download-4i8hnkw9/slpp/pip-egg-info
         cwd: /tmp/tmpwfrovct9/pip-download-4i8hnkw9/slpp/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/tmpwfrovct9/pip-download-4i8hnkw9/slpp/setup.py", line 5, in <module>
        with open(path.join(cur_dir, 'README.markdown'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwfrovct9/pip-download-4i8hnkw9/slpp/README.markdown'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by SirAnthony** [comment]
Thanks, will update update in repo today.
